### ISSUE TITLE
Step 8 is not clear enough.

### ISSUE THREAD

**Issue by jmmoore** [nullbitsco/docs#41]
It's very easy to read step 8 incorrectly and put screws in the bottom of the main board.

A caption on the picture or a change of phrasing or a pic of the top as well as the bottom?

Some way to make it clear which way things go. If it is done incorrectly you have to desolder every switch to fix.

**Comment by jaygreco** [comment]
Can you clarify with a picture, by chance? It sounds like this is an issue you ran into -- if so, a quick pic would be helpful.

**Comment by jmmoore** [comment]
I screwed the standoffs onto the wrong side of the board, thinking that they were necessary for the pcb plate the switches click into. I was wrong.

When I went to attach the acrylic, there were already screws in the bottom of the board.

I had to desolder all of the switches in order to put the standoffs on the correct side.

The note about the plate I think is misleading or led me to incorrectly assume that the pcb plate requires screws (which it doesn't).

**Comment by jaygreco** [comment]
Got it, makes sense! I'll update the build guide to make this more clear. 

Thanks for taking the time to make this issue and let me know. Apologies for the headache here.

**Comment by jmmoore** [comment]
For sure! I appreciate your responsiveness on a Sunday! For the record I totally understand why the pcb plate has holes in it. It just happened to lead me astray this time 😂

**Comment by jaygreco** [comment]
Tracking this in #17 moving forward
